a=input('digite algo ')
print(' o tipo primitivo desse valor é ', type(a))
print('o que você digitou tem somente espaços?',a.isspace())
print('é um numero?', a.isnumeric())
print('é alfabetico?', a.isalpha())
print('é alfanumerico?',a.isalnum())
print('está em maiuscula?', a.isupper())
print('esta em minuscula?',a.islower())
print('esta captalizada?',a.istitle())
